### ISSUE TITLE
broken links in github user documentation

### ISSUE THREAD

**Issue by capsulecorplab** [carlosperate/jekyll-theme-rtd#19]
links in https://carlosperate.github.io/jekyll-theme-rtd/ redirect to 404 page

**Comment by carlosperate** [comment]
Thanks for the report @capsulecorplab, do you have a specific link that is broken now?
I think the problem might have been with my domain, which i fix last week, sorry! 😅

**Comment by capsulecorplab** [comment]
It seems to work now!

**Comment by carlosperate** [comment]
Awesome, thanks @capsulecorplab!
